version: "3.3"
services:
  swagger-editor:
    image: swaggerapi/swagger-editor:v4.6.0
    container_name: "swagger-editor"
    ports:
      - "8081:8080"
    networks:
      - swagger

  swagger-ui:
    image: swaggerapi/swagger-ui:v4.15.5
    container_name: "swagger-ui"
    ports:
      - "8082:8080"
    volumes:
      - type: bind
        source: ./swagger/openapi.yaml
        target: /openapi.yaml
    environment:
      SWAGGER_JSON: /openapi.yaml
    networks:
      - swagger
networks:
  swagger:
    external: true