global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 1m
scrape_configs:
- job_name: cflogs_metrics
  metrics_path: /v1/metrics
  scrape_interval: 15s
  static_configs:
    - targets: ["host.docker.internal:3101"]
      labels:
        instance_name: 'nathan_local'