web:
  image: 'gitlab/gitlab-ee:latest'
  restart: always
  hostname: 'gitlab.nathan.local'
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'https://gitlab.nathan.local'
      # Add any other gitlab.rb configuration here, each on its own line
  ports:
    - '80:80'
    - '443:443'
    - '22:22'
  volumes:
    - '$GITLAB_HOME/config:/etc/gitlab'
    - '$GITLAB_HOME/logs:/var/log/gitlab'
    - '$GITLAB_HOME/data:/var/opt/gitlab'