version: "3.7"
services:
  mongodb-server:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: nathan123
    volumes:
      - mongodb-vol:/data/db
      - mongodb-config:/data/configdb
    ports:
      - "27017:27017" #we use host's port number 27017
volumes:
    mongodb-vol:
      name: mongodb-vol
    mongodb-config:
      name: mongodb-config