version: "3.7"
services:
  mongodb-server:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: nathan123
    volumes:
      - mongo-vol:/var/lib/mongo/data/
    ports:
      - "27017:27017" #we use host's port number 27017
volumes:
  mongo-vol: