version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq-local'
    environment:
      RABBITMQ_DEFAULT_USER: nathan
      RABBITMQ_DEFAULT_PASS: nathan123
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - rabbitmq-vol:/var/lib/rabbitmq
        - rabbitmq-log-vol:/var/log/rabbitmq
    networks:
        - rabbitmq_net

networks:
  rabbitmq_net:
    driver: bridge

volumes:
  rabbitmq-vol:
    name: rabbitmq-vol
  rabbitmq-log-vol:
    name: rabbitmq-log-vol